// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpvoedwxliaxojzbekvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwdm9lZHd4bGlheG9qemJla3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDA4MzMsImV4cCI6MjA3MDgxNjgzM30.A2oHCXF0ca8fjmEoHv2jz2l20GHgVNTV8wavml12ehA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});